openapi: 3.0.3

info:
  title: Pets Adoption API
  version: 1.0.0
  description: |
    API REST desarrollada con Node.js, Express, MongoDB Atlas y Passport JWT.

    ## Funcionalidades
    - Registro y login de usuarios
    - Autenticación JWT
    - CRUD de mascotas
    - Sistema de adopciones
    - Docker y Kubernetes
    - Swagger Documentation

servers:
  - url: http://localhost:8080
    description: Servidor local

  - url: http://localhost:30759
    description: Kubernetes NodePort

tags:
  - name: Users
    description: Operaciones relacionadas a usuarios

  - name: Auth
    description: Autenticación y sesiones

  - name: Session
    description: Sesión autenticada actual

  - name: Pets
    description: Gestión de mascotas

  - name: Adoptions
    description: Gestión de adopciones

paths:

  /api/users/register:
    post:
      summary: Registra un nuevo usuario.
      tags:
        - Users

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'

      responses:
        "201":
          description: Usuario creado correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        "400":
          description: Datos inválidos o email ya existente.

        "500":
          description: Error del servidor.

  /api/users:
    get:
      summary: Obtiene todos los usuarios.
      tags:
        - Users

      security:
        - bearerAuth: []

      responses:
        "200":
          description: Lista de usuarios.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

        "401":
          description: Unauthorized.

        "403":
          description: No autorizado.

        "500":
          description: Error del servidor.

  /api/users/{id}:
    get:
      summary: Obtiene un usuario por ID.
      tags:
        - Users

      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Usuario encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        "404":
          description: Usuario no encontrado.

        "500":
          description: Error del servidor.

    patch:
      summary: Actualiza un usuario.
      tags:
        - Users

      security:
        - bearerAuth: []

      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'

      responses:
        "200":
          description: Usuario actualizado correctamente.

        "401":
          description: Unauthorized.

        "403":
          description: No autorizado.

        "500":
          description: Error del servidor.

    delete:
      summary: Elimina un usuario.
      tags:
        - Users

      security:
        - bearerAuth: []

      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Usuario eliminado correctamente.

        "401":
          description: Unauthorized.

        "403":
          description: No autorizado.

        "404":
          description: Usuario no encontrado.

        "500":
          description: Error del servidor.

  /api/auth/login:
    post:
      summary: Inicia sesión de un usuario.
      tags:
        - Auth

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'

      responses:
        "200":
          description: Login exitoso.
          content:
            application/json:
              schema:
                type: object

                properties:
                  message:
                    type: string

                  user:
                    $ref: '#/components/schemas/User'

        "401":
          description: Usuario no encontrado o contraseña incorrecta.

        "500":
          description: Error del servidor.

  /api/auth/logout:
    post:
      summary: Cierra la sesión del usuario.
      tags:
        - Auth

      security:
        - bearerAuth: []

      responses:
        "200":
          description: Logout exitoso.

        "500":
          description: Error del servidor.

  /session/current:
    get:
      summary: Obtiene la sesión actual autenticada.
      tags:
        - Session

      security:
        - bearerAuth: []

      responses:
        "200":
          description: Sesión obtenida correctamente.
          content:
            application/json:
              schema:
                type: object

                properties:
                  first_name:
                    type: string

                  email:
                    type: string

                  role:
                    type: string

        "401":
          description: Unauthorized.

        "500":
          description: Error del servidor.

  /api/pets:
    get:
      summary: Obtiene todas las mascotas.
      tags:
        - Pets

      responses:
        "200":
          description: Lista de mascotas obtenida correctamente.
          content:
            application/json:
              schema:
                type: array

                items:
                  $ref: '#/components/schemas/Pet'

        "500":
          description: Error del servidor.

    post:
      summary: Crea una nueva mascota.
      tags:
        - Pets

      security:
        - bearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePet'

      responses:
        "201":
          description: Mascota creada correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

        "400":
          description: Error de validación.

        "500":
          description: Error del servidor.

  /api/pets/{pid}:
    get:
      summary: Obtiene una mascota por ID.
      tags:
        - Pets

      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Mascota encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

        "404":
          description: Mascota no encontrada.

        "500":
          description: Error del servidor.

    put:
      summary: Actualiza una mascota por ID.
      tags:
        - Pets

      security:
        - bearerAuth: []

      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePet'

      responses:
        "200":
          description: Mascota actualizada correctamente.

        "401":
          description: Unauthorized.

        "403":
          description: No autorizado.

        "500":
          description: Error del servidor.

    delete:
      summary: Elimina una mascota por ID.
      tags:
        - Pets

      security:
        - bearerAuth: []

      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Mascota eliminada correctamente.

        "401":
          description: Unauthorized.

        "403":
          description: No autorizado.

        "404":
          description: Mascota no encontrada.

        "500":
          description: Error del servidor.

  /api/adoptions:
    get:
      summary: Obtiene todas las adopciones.
      tags:
        - Adoptions

      responses:
        "200":
          description: Lista de adopciones.
          content:
            application/json:
              schema:
                type: array

                items:
                  $ref: '#/components/schemas/Adoption'

        "500":
          description: Error del servidor.

  /api/adoptions/{aid}:
    get:
      summary: Obtiene una adopción por ID.
      tags:
        - Adoptions

      parameters:
        - name: aid
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Adopción encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adoption'

        "404":
          description: Adopción no encontrada.

        "500":
          description: Error del servidor.

  /api/adoptions/{uid}/{pid}:
    post:
      summary: Crea una nueva adopción.
      tags:
        - Adoptions

      security:
        - bearerAuth: []

      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string

        - name: pid
          in: path
          required: true
          schema:
            type: string

      responses:
        "201":
          description: Adopción creada correctamente.

        "400":
          description: Mascota ya adoptada.

        "500":
          description: Error del servidor.

components:

  securitySchemes:

    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    User:
      type: object

      properties:

        _id:
          type: string

        first_name:
          type: string

        email:
          type: string

        role:
          type: string

        pets:
          type: array

          items:
            type: string

      example:
        _id: 69fbdaa4042e0393267e33e8
        first_name: Martin
        email: admin@test.com
        role: user
        pets: []

    Pet:
      type: object

      properties:

        _id:
          type: string

        name:
          type: string

        species:
          type: string

        breed:
          type: string

        age:
          type: number

        size:
          type: string

        description:
          type: string

        status:
          type: string

        images:
          type: array

          items:
            type: string

        vaccinated:
          type: boolean

        stock:
          type: number

      example:
        _id: 69fbddf7e065d02a3b317f9a
        name: Rocky
        species: Perro
        breed: Labrador
        age: 3
        size: Grande
        description: Perro muy juguetón y amigable
        status: disponible
        images:
          - https://imagen1.jpg
          - https://imagen2.jpg
        vaccinated: true
        stock: 1

    Adoption:
      type: object

      properties:

        _id:
          type: string

        owner:
          $ref: '#/components/schemas/User'

        pet:
          $ref: '#/components/schemas/Pet'

      example:
        _id: 6812fa9cc0f1f92ab3aa1234

        owner:
          _id: 6812fa9cc0f1f92ab3aa1111
          first_name: Martin
          email: admin@test.com

        pet:
          _id: 6812fa9cc0f1f92ab3aa2222
          name: Rocky
          species: Perro

    RegisterUser:
      type: object

      required:
        - first_name
        - email
        - password

      properties:

        first_name:
          type: string

        email:
          type: string

        password:
          type: string

      example:
        first_name: Martin
        email: admin@test.com
        password: "123456"

    LoginUser:
      type: object

      required:
        - email
        - password

      properties:

        email:
          type: string

        password:
          type: string

      example:
        email: admin@test.com
        password: "123456"

    CreatePet:
      type: object

      required:
        - name
        - species
        - description

      properties:

        name:
          type: string

        species:
          type: string

        breed:
          type: string

        age:
          type: number

        size:
          type: string

        description:
          type: string

        status:
          type: string

        images:
          type: array

          items:
            type: string

        vaccinated:
          type: boolean

        stock:
          type: number

      example:
        name: Rocky
        species: Perro
        breed: Labrador
        age: 3
        size: Grande
        description: Perro muy juguetón y amigable
        status: disponible
        images:
          - https://imagen1.jpg
          - https://imagen2.jpg
        vaccinated: true
        stock: 1

    UpdatePet:
      type: object

      properties:

        stock:
          type: number

        status:
          type: string

      example:
        stock: 5
        status: adoptado

    UpdateUser:
      type: object

      properties:

        first_name:
          type: string

        email:
          type: string

        role:
          type: string

      example:
        first_name: Martin Updated
        email: updated@test.com
        role: admin